name: flutter_application_for_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  enough_mail: ^2.1.3
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  flutter_scroll_to_top: ^2.3.0
  font_awesome_flutter: ^10.6.0
  google_fonts: 6.1.0
  provider: ^6.0.5
  responsive_builder: ^0.7.0
  televerse: ^1.11.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib\images\header_img_01.jpg
    - lib\images\portrait_for_header.png 
    - lib\images\project1.png
    - lib\images\project2.png
    - lib\images\project3.png
    - lib\images\project4.png
    - lib\images\project5.png
    - lib\images\project6.png

    
